# fly.toml app configuration file generated for silent-sun-2390 on 2023-10-01T22:23:13+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "silent-sun-2390"
primary_region = "arn"

[build]

[http_service]
  internal_port = 7777
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
